export const COUNTRIES = [
  { value: "US", label: "United States", flag: "🇺🇸" },
  { value: "CA", label: "Canada", flag: "🇨🇦" },
  { value: "GB", label: "United Kingdom", flag: "🇬🇧" },
  { value: "AU", label: "Australia", flag: "🇦🇺" },
  { value: "DE", label: "Germany", flag: "🇩🇪" },
  { value: "FR", label: "France", flag: "🇫🇷" },
  { value: "IT", label: "Italy", flag: "🇮🇹" },
  { value: "ES", label: "Spain", flag: "🇪🇸" },
  { value: "NL", label: "Netherlands", flag: "🇳🇱" },
  { value: "BE", label: "Belgium", flag: "🇧🇪" },
  { value: "CH", label: "Switzerland", flag: "🇨🇭" },
  { value: "AT", label: "Austria", flag: "🇦🇹" },
  { value: "SE", label: "Sweden", flag: "🇸🇪" },
  { value: "NO", label: "Norway", flag: "🇳🇴" },
  { value: "DK", label: "Denmark", flag: "🇩🇰" },
  { value: "FI", label: "Finland", flag: "🇫🇮" },
  { value: "PL", label: "Poland", flag: "🇵🇱" },
  { value: "CZ", label: "Czech Republic", flag: "🇨🇿" },
  { value: "HU", label: "Hungary", flag: "🇭🇺" },
  { value: "RO", label: "Romania", flag: "🇷🇴" },
  { value: "BG", label: "Bulgaria", flag: "🇧🇬" },
  { value: "HR", label: "Croatia", flag: "🇭🇷" },
  { value: "SI", label: "Slovenia", flag: "🇸🇮" },
  { value: "SK", label: "Slovakia", flag: "🇸🇰" },
  { value: "LT", label: "Lithuania", flag: "🇱🇹" },
  { value: "LV", label: "Latvia", flag: "🇱🇻" },
  { value: "EE", label: "Estonia", flag: "🇪🇪" },
  { value: "IE", label: "Ireland", flag: "🇮🇪" },
  { value: "PT", label: "Portugal", flag: "🇵🇹" },
  { value: "GR", label: "Greece", flag: "🇬🇷" },
  { value: "CY", label: "Cyprus", flag: "🇨🇾" },
  { value: "MT", label: "Malta", flag: "🇲🇹" },
  { value: "LU", label: "Luxembourg", flag: "🇱🇺" },
  { value: "IS", label: "Iceland", flag: "🇮🇸" },
  { value: "JP", label: "Japan", flag: "🇯🇵" },
  { value: "KR", label: "South Korea", flag: "🇰🇷" },
  { value: "CN", label: "China", flag: "🇨🇳" },
  { value: "IN", label: "India", flag: "🇮🇳" },
  { value: "BR", label: "Brazil", flag: "🇧🇷" },
  { value: "MX", label: "Mexico", flag: "🇲🇽" },
  { value: "AR", label: "Argentina", flag: "🇦🇷" },
  { value: "CL", label: "Chile", flag: "🇨🇱" },
  { value: "CO", label: "Colombia", flag: "🇨🇴" },
  { value: "PE", label: "Peru", flag: "🇵🇪" },
  { value: "VE", label: "Venezuela", flag: "🇻🇪" },
  { value: "UY", label: "Uruguay", flag: "🇺🇾" },
  { value: "PY", label: "Paraguay", flag: "🇵🇾" },
  { value: "BO", label: "Bolivia", flag: "🇧🇴" },
  { value: "EC", label: "Ecuador", flag: "🇪🇨" },
  { value: "GY", label: "Guyana", flag: "🇬🇾" },
  { value: "SR", label: "Suriname", flag: "🇸🇷" },
  { value: "ZA", label: "South Africa", flag: "🇿🇦" },
  { value: "EG", label: "Egypt", flag: "🇪🇬" },
  { value: "NG", label: "Nigeria", flag: "🇳🇬" },
  { value: "KE", label: "Kenya", flag: "🇰🇪" },
  { value: "GH", label: "Ghana", flag: "🇬🇭" },
  { value: "ET", label: "Ethiopia", flag: "🇪🇹" },
  { value: "TZ", label: "Tanzania", flag: "🇹🇿" },
  { value: "UG", label: "Uganda", flag: "🇺🇬" },
  { value: "RW", label: "Rwanda", flag: "🇷🇼" },
  { value: "BI", label: "Burundi", flag: "🇧🇮" },
  { value: "MW", label: "Malawi", flag: "🇲🇼" },
  { value: "ZM", label: "Zambia", flag: "🇿🇲" },
  { value: "ZW", label: "Zimbabwe", flag: "🇿🇼" },
  { value: "BW", label: "Botswana", flag: "🇧🇼" },
  { value: "NA", label: "Namibia", flag: "🇳🇦" },
  { value: "SZ", label: "Eswatini", flag: "🇸🇿" },
  { value: "LS", label: "Lesotho", flag: "🇱🇸" },
  { value: "MG", label: "Madagascar", flag: "🇲🇬" },
  { value: "MU", label: "Mauritius", flag: "🇲🇺" },
  { value: "SC", label: "Seychelles", flag: "🇸🇨" },
  { value: "KM", label: "Comoros", flag: "🇰🇲" },
  { value: "DJ", label: "Djibouti", flag: "🇩🇯" },
  { value: "SO", label: "Somalia", flag: "🇸🇴" },
  { value: "ER", label: "Eritrea", flag: "🇪🇷" },
  { value: "SD", label: "Sudan", flag: "🇸🇩" },
  { value: "SS", label: "South Sudan", flag: "🇸🇸" },
  { value: "CF", label: "Central African Republic", flag: "🇨🇫" },
  { value: "TD", label: "Chad", flag: "🇹🇩" },
  { value: "CM", label: "Cameroon", flag: "🇨🇲" },
  { value: "GQ", label: "Equatorial Guinea", flag: "🇬🇶" },
  { value: "GA", label: "Gabon", flag: "🇬🇦" },
  { value: "CG", label: "Republic of the Congo", flag: "🇨🇬" },
  { value: "CD", label: "Democratic Republic of the Congo", flag: "🇨🇩" },
  { value: "AO", label: "Angola", flag: "🇦🇴" },
  { value: "ST", label: "São Tomé and Príncipe", flag: "🇸🇹" },
  { value: "CV", label: "Cape Verde", flag: "🇨🇻" },
  { value: "GM", label: "Gambia", flag: "🇬🇲" },
  { value: "SN", label: "Senegal", flag: "🇸🇳" },
  { value: "GN", label: "Guinea", flag: "🇬🇳" },
  { value: "GW", label: "Guinea-Bissau", flag: "🇬🇼" },
  { value: "SL", label: "Sierra Leone", flag: "🇸🇱" },
  { value: "LR", label: "Liberia", flag: "🇱🇷" },
  { value: "CI", label: "Ivory Coast", flag: "🇨🇮" },
  { value: "BF", label: "Burkina Faso", flag: "🇧🇫" },
  { value: "ML", label: "Mali", flag: "🇲🇱" },
  { value: "NE", label: "Niger", flag: "🇳🇪" },
  { value: "MR", label: "Mauritania", flag: "🇲🇷" },
  { value: "TN", label: "Tunisia", flag: "🇹🇳" },
  { value: "DZ", label: "Algeria", flag: "🇩🇿" },
  { value: "MA", label: "Morocco", flag: "🇲🇦" },
  { value: "LY", label: "Libya", flag: "🇱🇾" },
  { value: "SA", label: "Saudi Arabia", flag: "🇸🇦" },
  { value: "AE", label: "United Arab Emirates", flag: "🇦🇪" },
  { value: "QA", label: "Qatar", flag: "🇶🇦" },
  { value: "KW", label: "Kuwait", flag: "🇰🇼" },
  { value: "BH", label: "Bahrain", flag: "🇧🇭" },
  { value: "OM", label: "Oman", flag: "🇴🇲" },
  { value: "YE", label: "Yemen", flag: "🇾🇪" },
  { value: "JO", label: "Jordan", flag: "🇯🇴" },
  { value: "LB", label: "Lebanon", flag: "🇱🇧" },
  { value: "SY", label: "Syria", flag: "🇸🇾" },
  { value: "IQ", label: "Iraq", flag: "🇮🇶" },
  { value: "IR", label: "Iran", flag: "🇮🇷" },
  { value: "TR", label: "Turkey", flag: "🇹🇷" },
  { value: "IL", label: "Israel", flag: "🇮🇱" },
  { value: "PS", label: "Palestine", flag: "🇵🇸" },
  { value: "TH", label: "Thailand", flag: "🇹🇭" },
  { value: "VN", label: "Vietnam", flag: "🇻🇳" },
  { value: "MY", label: "Malaysia", flag: "🇲🇾" },
  { value: "SG", label: "Singapore", flag: "🇸🇬" },
  { value: "ID", label: "Indonesia", flag: "🇮🇩" },
  { value: "PH", label: "Philippines", flag: "🇵🇭" },
  { value: "MM", label: "Myanmar", flag: "🇲🇲" },
  { value: "LA", label: "Laos", flag: "🇱🇦" },
  { value: "KH", label: "Cambodia", flag: "🇰🇭" },
  { value: "BD", label: "Bangladesh", flag: "🇧🇩" },
  { value: "LK", label: "Sri Lanka", flag: "🇱🇰" },
  { value: "NP", label: "Nepal", flag: "🇳🇵" },
  { value: "BT", label: "Bhutan", flag: "🇧🇹" },
  { value: "MV", label: "Maldives", flag: "🇲🇻" },
  { value: "PK", label: "Pakistan", flag: "🇵🇰" },
  { value: "AF", label: "Afghanistan", flag: "🇦🇫" },
  { value: "TJ", label: "Tajikistan", flag: "🇹🇯" },
  { value: "KG", label: "Kyrgyzstan", flag: "🇰🇬" },
  { value: "UZ", label: "Uzbekistan", flag: "🇺🇿" },
  { value: "TM", label: "Turkmenistan", flag: "🇹🇲" },
  { value: "KZ", label: "Kazakhstan", flag: "🇰🇿" },
  { value: "MN", label: "Mongolia", flag: "🇲🇳" },
  { value: "RU", label: "Russia", flag: "🇷🇺" },
  { value: "UA", label: "Ukraine", flag: "🇺🇦" },
  { value: "BY", label: "Belarus", flag: "🇧🇾" },
  { value: "MD", label: "Moldova", flag: "🇲🇩" },
  { value: "GE", label: "Georgia", flag: "🇬🇪" },
  { value: "AM", label: "Armenia", flag: "🇦🇲" },
  { value: "AZ", label: "Azerbaijan", flag: "🇦🇿" },
  { value: "AL", label: "Albania", flag: "🇦🇱" },
  { value: "MK", label: "North Macedonia", flag: "🇲🇰" },
  { value: "ME", label: "Montenegro", flag: "🇲🇪" },
  { value: "RS", label: "Serbia", flag: "🇷🇸" },
  { value: "BA", label: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { value: "XK", label: "Kosovo", flag: "🇽🇰" },
  { value: "NZ", label: "New Zealand", flag: "🇳🇿" },
  { value: "FJ", label: "Fiji", flag: "🇫🇯" },
  { value: "PG", label: "Papua New Guinea", flag: "🇵🇬" },
  { value: "SB", label: "Solomon Islands", flag: "🇸🇧" },
  { value: "VU", label: "Vanuatu", flag: "🇻🇺" },
  { value: "NC", label: "New Caledonia", flag: "🇳🇨" },
  { value: "PF", label: "French Polynesia", flag: "🇵🇫" },
  { value: "TO", label: "Tonga", flag: "🇹🇴" },
  { value: "WS", label: "Samoa", flag: "🇼🇸" },
  { value: "KI", label: "Kiribati", flag: "🇰🇮" },
  { value: "TV", label: "Tuvalu", flag: "🇹🇻" },
  { value: "NR", label: "Nauru", flag: "🇳🇷" },
  { value: "PW", label: "Palau", flag: "🇵🇼" },
  { value: "MH", label: "Marshall Islands", flag: "🇲🇭" },
  { value: "FM", label: "Micronesia", flag: "🇫🇲" },
  { value: "CK", label: "Cook Islands", flag: "🇨🇰" },
  { value: "NU", label: "Niue", flag: "🇳🇺" },
  { value: "TK", label: "Tokelau", flag: "🇹🇰" },
  { value: "AS", label: "American Samoa", flag: "🇦🇸" },
  { value: "GU", label: "Guam", flag: "🇬🇺" },
  { value: "MP", label: "Northern Mariana Islands", flag: "🇲🇵" },
  { value: "PR", label: "Puerto Rico", flag: "🇵🇷" },
  { value: "VI", label: "U.S. Virgin Islands", flag: "🇻🇮" },
  { value: "AI", label: "Anguilla", flag: "🇦🇮" },
  { value: "VG", label: "British Virgin Islands", flag: "🇻🇬" },
  { value: "MS", label: "Montserrat", flag: "🇲🇸" },
  { value: "KN", label: "Saint Kitts and Nevis", flag: "🇰🇳" },
  { value: "AG", label: "Antigua and Barbuda", flag: "🇦🇬" },
  { value: "DM", label: "Dominica", flag: "🇩🇲" },
  { value: "LC", label: "Saint Lucia", flag: "🇱🇨" },
  { value: "VC", label: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  { value: "BB", label: "Barbados", flag: "🇧🇧" },
  { value: "GD", label: "Grenada", flag: "🇬🇩" },
  { value: "TT", label: "Trinidad and Tobago", flag: "🇹🇹" },
  { value: "JM", label: "Jamaica", flag: "🇯🇲" },
  { value: "HT", label: "Haiti", flag: "🇭🇹" },
  { value: "DO", label: "Dominican Republic", flag: "🇩🇴" },
  { value: "CU", label: "Cuba", flag: "🇨🇺" },
  { value: "BS", label: "Bahamas", flag: "🇧🇸" },
  { value: "TC", label: "Turks and Caicos Islands", flag: "🇹🇨" },
  { value: "KY", label: "Cayman Islands", flag: "🇰🇾" },
  { value: "BM", label: "Bermuda", flag: "🇧🇲" },
  { value: "FK", label: "Falkland Islands", flag: "🇫🇰" },
  {
    value: "GS",
    label: "South Georgia and the South Sandwich Islands",
    flag: "🇬🇸",
  },
  { value: "GF", label: "French Guiana", flag: "🇬🇫" },
  { value: "SR", label: "Suriname", flag: "🇸🇷" },
  { value: "GY", label: "Guyana", flag: "🇬🇾" },
  { value: "BZ", label: "Belize", flag: "🇧🇿" },
  { value: "GT", label: "Guatemala", flag: "🇬🇹" },
  { value: "SV", label: "El Salvador", flag: "🇸🇻" },
  { value: "HN", label: "Honduras", flag: "🇭🇳" },
  { value: "NI", label: "Nicaragua", flag: "🇳🇮" },
  { value: "CR", label: "Costa Rica", flag: "🇨🇷" },
  { value: "PA", label: "Panama", flag: "🇵🇦" },
];
